spring:
  application:
    name: epia
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@192.168.12.150:1521:orcl
#    username: epia
#    password: epia

server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
    max-threads: 2000
    max-connections: 20000
  servlet:
    context-path: /${spring.application.name}/








